export const TOOL_NAMES = [
  'proxmox_node',
  'proxmox_cluster',
  'proxmox_node_service',
  'proxmox_node_log',
  'proxmox_node_task',
  'proxmox_node_info',
  'proxmox_node_config',
  'proxmox_node_subscription',
  'proxmox_apt',
  'proxmox_node_bulk',
  'proxmox_node_power',
  'proxmox_node_replication',
  'proxmox_node_network_iface',
  'proxmox_guest_list',
  'proxmox_guest_status',
  'proxmox_guest_config',
  'proxmox_guest_pending',
  'proxmox_guest_feature',
  'proxmox_guest_rrddata',
  'proxmox_create_lxc',
  'proxmox_create_vm',
  'proxmox_get_next_vmid',
  'proxmox_ha_resource',
  'proxmox_ha_group',
  'proxmox_cluster_firewall_rule',
  'proxmox_cluster_firewall_group',
  'proxmox_cluster_firewall',
  'proxmox_cluster_firewall_alias',
  'proxmox_cluster_firewall_ipset',
  'proxmox_cluster_firewall_ipset_entry',
  'proxmox_cluster_backup_job',
  'proxmox_cluster_replication_job',
  'proxmox_cluster_config',
  'proxmox_sdn_vnet',
  'proxmox_sdn_zone',
  'proxmox_sdn_controller',
  'proxmox_sdn_subnet',
  'proxmox_user',
  'proxmox_group',
  'proxmox_role',
  'proxmox_acl',
  'proxmox_domain',
  'proxmox_user_token',
  'proxmox_pool',
  'proxmox_storage_config',
  'proxmox_storage_content',
  'proxmox_file_restore',
  'proxmox_ceph',
  'proxmox_ceph_osd',
  'proxmox_ceph_mon',
  'proxmox_ceph_mds',
  'proxmox_ceph_pool',
  'proxmox_ceph_fs',
  'proxmox_guest_start',
  'proxmox_guest_stop',
  'proxmox_guest_reboot',
  'proxmox_guest_shutdown',
  'proxmox_guest_delete',
  'proxmox_guest_pause',
  'proxmox_guest_resume',
  'proxmox_guest_clone',
  'proxmox_guest_resize',
  'proxmox_guest_config_update',
  'proxmox_guest_migrate',
  'proxmox_guest_template',

  'proxmox_agent_info',
  'proxmox_agent_hw',
  'proxmox_agent_exec',
  'proxmox_agent_file',
  'proxmox_agent_freeze',
  'proxmox_agent_power',
  'proxmox_agent_user',
  'proxmox_guest_firewall_rule',
  'proxmox_console_vnc',
  'proxmox_console_term',
  'proxmox_console_spice',
  'proxmox_guest_snapshot',
  'proxmox_backup',
  'proxmox_vm_disk',
  'proxmox_lxc_mountpoint',
  'proxmox_guest_disk_resize',

  'proxmox_guest_disk_move',
  'proxmox_guest_network',
  'proxmox_node_disk',
  'proxmox_node_disk_admin',
  'proxmox_cloudinit',
  'proxmox_certificate',
  'proxmox_acme_cert',
  'proxmox_acme_account',
  'proxmox_acme_info',
  'proxmox_notification',
  'proxmox_lxc_exec',
] as const;

export type ToolName = (typeof TOOL_NAMES)[number];

export type PermissionLevel = 'basic' | 'elevated';

export interface ToolResponse {
  content: Array<{
    type: 'text';
    text: string;
  }>;
  isError?: boolean;
}

export function createToolResponse(text: string, isError = false): ToolResponse {
  return {
    content: [{ type: 'text', text }],
    isError,
  };
}
